version: '3'
services:
  cmp_json_service:
    container_name: cmp_json
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
#    command:
#      python3 generate_file.py
#      python3 cmp_json.py
#    command: sleep 1d
    command: bash script.sh

